---
name: codde_protocol
description: Multi Communication protocol in heart of the C.O.D.D.E. Pi framework
version: 0.1.3
homepage: https://codde-pi.com
repository: https://github.com/codde_pi/codde_protocol

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: ^2.0.0-dev.28
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.8
  ffigen: ^11.0.0
  freezed: ^2.4.7
  lints: ^3.0.0
  mockito: ^5.4.2
  test: ^1.21.0
