[package]
name = "codde_protocol_client"
version = "0.1.4"
edition = "2021"
authors = ["Mathis Lecomte <vm.lecomte@gmail.com>"]
description = "Multi Communication protocol in heart of the C.O.D.D.E. Pi framework"
readme = "../../../../README.md"
license-file = "../../../../LICENSE"
keywords = ["rust", "python", "codde_pi", "iot"]
homepage = "https://github.com/codde-pi/codde_protocol"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.30"
quote = "1.0.35"
serde = {version= "1.0.196",  features = ["derive"] }
syn = "2.0.48"
codde_protocol_derive = "0.1.0"
cbor = "0.4.1"
typetag = "0.2.15"
rmp-serde = "1.1.2"
anyhow = "1.0.79"
cbindgen = "0.26.0"

[build-dependencies]
flutter_rust_bridge_codegen = "2.0.0-dev.36"

[lib]
name = "codde_protocol"
crate-type = ["staticlib", "cdylib", "rlib"]
